
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtphQabzIyG_hw617jPZktk71tUOVfwE',
    authDomain: 'thamizh-faf1a.firebaseapp.com',
    projectId: 'thamizh-faf1a',
    storageBucket: 'thamizh-faf1a.appspot.com',
    messagingSenderId: '419123520013',
    appId: '1:419123520013:web:a10757344d45442de72b44'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARY240uL-hOdBlldD94j53M1Ll4KKaoo4',
    appId: '1:419123520013:android:4c068a451ce9cc21e72b44',
    messagingSenderId: '419123520013',
    projectId: 'thamizh-faf1a',
    storageBucket: 'thamizh-faf1a.firebasestorage.app'
  );
}
